version: '3'
services:
  database:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=shop
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/lib/postgresql/data/application
    volumes:
      - ../../../data:/var/lib/postgresql/data/application
  pgadmin:
    image: dpage/pgadmin4:4
    ports:
      - "8000:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=training@sages.pl
      - PGADMIN_DEFAULT_PASSWORD=admin
  mongo:
    image: mongo
    ports:
     - "27017:27017"
  cassandra:
    image: cassandra
    ports:
      - "9043:9042"

